name: Units CI

on: [push, pull_request]

jobs:
  test-frontend:
    name: Unit-Tests QA (Frontend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Linting
        working-directory: ./frontend
        run: npm run lint

      - name: Testing
        working-directory: ./frontend
        run: npm test

  test-backend:
    name: Unit-Tests QA (Backend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y python3.11 python3.11-distutils

      - name: Install coverage
        run: python3.11 -m pip install coverage

      - name: Test Backend
        working-directory: ./backend
        run: |
          coverage run -m unittest src/test_calculator.py
          coverage report -m
